# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dr. Peter Jesch
subtitle: Rechtsanwalts GmbH
lang: de-AT
company:
  email: office@jesch.law
  location: Moosstraße 37, 5020 Salzburg
  location-link: https://goo.gl/maps/kpbCWj2NMQFwj3p6A # https://stackoverflow.com/a/39341021
  phone: + 43 662 848583
  fax: +43 662 848583-20
  imprint:
    ceo: Rechtsanwalt Dr. Peter Jesch
    name: Dr. Peter Jesch Rechtsanwalts GmbH
    address:
      street: Moosstraße 37
      zip: 5020
      city: Salzburg
      country: Österreich
#    firmensitz: Sitz Salzburg
#    firmennummer: FN 45282t
    gerichtsstand: Landesgericht Salzburg
    aufsichtsbehoerde: Rechtsanwaltskammer Salzburg
    uid: ATU34482805
description: >
  Wir sind für Sie da!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

google:
  site-verification: q_gqTtu5Y0hW89Edt9yQAoVefhlrAcluCtcfGSNdiyM
  maps: # https://stackoverflow.com/a/39341021
    embed-link: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2680.6433222690134!2d13.02536561563685!3d47.78836387919713!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47769045046a7e51%3A0x11a7f22f7ba16dfe!2sMoosstra%C3%9Fe%2037%2C%205020%20Salzburg!5e0!3m2!1sde!2sat!4v1596547649293!5m2!1sde!2sat

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
