# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dr. Peter Jesch
subtitle: Rechtsanwalts GmbH
lang: de-AT
company:
  email: office@jesch.law
  location: Reichenhaller Straße 5, 5020 Salzburg
  location-link: https://goo.gl/maps/FGfPwZ75vKB2
  phone: + 43 662 848583
  fax: +43 662 848583-20
  imprint:
    ceo: "Geschäftsführer: Dr. Peter Jesch"
    name: Dr. Peter Jesch Rechtsanwalts GmbH
    address:
      street: Reichenhaller Straße 5
      zip: 5020
      city: Salzburg
      country: Österreich
    firmensitz: Sitz Salzburg
    firmennummer: FN 45282t
    gerichtsstand: Landesgericht Salzburg
    aufsichtsbehoerde: Rechtsanwaltskammer Salzburg
    uid: ATU34646005
description: >
  Unsere Mission: Ihre Wertschöpfung durch selbst-lernende,
  daten-getriebene Machine Learning Algorithmen zur vollen
  Entfaltung zu bringen!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

google:
  site-verification: q_gqTtu5Y0hW89Edt9yQAoVefhlrAcluCtcfGSNdiyM
  maps:
    embed-link: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2680.1340751364023!2d13.033992751438218!3d47.79823668261059!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4776906636c6c52f%3A0x81930bb3ecfa9d59!2sReichenhaller+Str.+5%2C+5020+Salzburg!5e0!3m2!1sde!2sat!4v1528876988689

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
